(self.AMP=self.AMP||[]).push({n:"amp-auto-ads",v:"1908222134250",f:(function(AMP,_){
var g,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},k;if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var l;a:{var ba={a:!0},n={};try{n.__proto__=ba;l=n.a;break a}catch(a){}l=!1}k=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var p=k,ca=Object.prototype.toString;function q(a){return a||{}};function u(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function v(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};self.log=self.log||{user:null,dev:null,userForEmbed:null};var x=self.log;function y(){if(!x.user)throw Error("failed to call initLogConstructor");return x.user}function z(a,b){y().assert(a,b,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};var da={type:!0};function A(a,b){if(!a[b])return{};if("[object Object]"!==ca.call(a[b])||Array.isArray(a[b]))return y().warn("amp-auto-ads",b+" property not an object"),{};b=a[b];var c={},d;for(d in b)if(da[d]||v(d,"data-")){var e=typeof b[d];"number"!=e&&"string"!=e&&"boolean"!=e?y().warn("amp-auto-ads","Attribute type not supported: "+e):c[d]=String(b[d])}else y().warn("amp-auto-ads","Attribute not whitlisted: "+d);return c};function ea(a){return a?{top:a.top,bottom:a.bottom,left:a.left,right:a.right}:a};function fa(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b}function ha(a){return new Promise(function(b){b(a())})};function B(){var a=100;this.M=a;this.A=this.C=0;this.w=Object.create(null)}B.prototype.has=function(a){return!!this.w[a]};B.prototype.get=function(a){var b=this.w[a];if(b)return b.access=++this.A,b.payload};
B.prototype.put=function(a,b){this.has(a)||this.C++;this.w[a]={payload:b,access:this.A};if(!(this.C<=this.M)){if(x.dev)a=x.dev;else throw Error("failed to call initLogConstructor");a.warn("lru-cache","Trimming LRU cache");a=this.w;var c=this.A+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.C--)}};q({c:!0,v:!0,a:!0,ad:!0,action:!0});var D,E;
function F(a){var b;D||(D=self.document.createElement("a"),E=self.UrlCache||(self.UrlCache=new B));var c=b?null:E,d=D;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=
d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a};function G(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return H(a,b)}function I(a,b){var c=J(a);c=J(c);c=c.isSingleDoc()?c.win:c;return H(c,b)}function J(a){return a.nodeType?G((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function H(a,b){var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var L;function M(a,b,c){a=a.createElement(b);for(var d in c)a.setAttribute(d,c[d]);return a}function ia(a,b){for(var c;a&&a!==c;a=a.parentElement)if(b(a))return a;return null}function ja(a,b){return a.closest?a.closest(b):ia(a,function(a){var c=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return c?c.call(a,b):!1})}
function ka(a,b){if(void 0!==L)var c=L;else{try{var d=a.ownerDocument,e=d.createElement("div"),f=d.createElement("div");e.appendChild(f);c=e.querySelector(":scope div")===f}catch(h){c=!1}c=L=c}c?a=a.querySelectorAll(b.replace(/^|,/g,"$&:scope ")):(a.classList.add("i-amphtml-scoped"),b=b.replace(/^|,/g,"$&.i-amphtml-scoped "),b=a.querySelectorAll(b),a.classList.remove("i-amphtml-scoped"),a=b);return a}
function la(a){v(a.tagName,"AMP-");if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new fa;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};function N(a){return I(a,"viewport")};function O(a){var b=I(a,"resources"),c=b.getResourceForElementOptional(a);if(c)return c.getPageLayoutBoxAsync();var d=G(a.ownerDocument.defaultView,"vsync");return d.measurePromise(function(){return N(a).getLayoutRect(a)})};var ma=["AMP-SIDEBAR","AMP-APP-BANNER"],na={1:function(a,b){a.parentNode.insertBefore(b,a)},4:function(a,b){a.parentNode.insertBefore(b,a.nextSibling)},2:function(a,b){a.insertBefore(b,a.firstChild)},3:function(a,b){a.appendChild(b)}};function P(a,b,c,d,e,f){this.ampdoc=a;this.U=I(b,"resources");this.J=N(b);this.o=b;this.T=c;this.P=d;this.K=e;this.G=f;this.D=null;this.j=0}P.prototype.getAdElement=function(){return this.D};
P.prototype.getEstimatedPosition=function(){var a=this;return O(this.o).then(function(b){a:switch(a.T){case 1:case 2:b=b.top;break a;case 3:case 4:b=b.bottom;break a;default:throw Error("Unknown position");}return b})};
P.prototype.placeAd=function(a,b,c,d){var e=this;return this.getEstimatedPosition().then(function(f){return c.isTooNearAnAd(f).then(function(c){if(c)return e.j=3,e.j;e.D=oa(e,a,b.width);e.P(e.o,e.getAdElement());return pa(e,b,d).then(function(a){return la(e.getAdElement()).then(function(){return e.getAdElement().whenBuilt()}).then(function(){return e.U.attemptChangeSize(e.getAdElement(),a.height,a.width,a.margins)}).then(function(){e.j=2;return e.j},function(){e.j=1;return e.j})})})})};
function pa(a,b,c){var d=a.J.getWidth();if(c&&1200>=d){var e=a.J.getHeight(),f=qa(d,e),h=ea(a.G);return O(a.o).then(function(b){var c;(c=a.ampdoc.win.getComputedStyle(a.o))||(c=Object.create(null));c=c.direction;0!==b.left&&(h=h||{},"rtl"==c?h.right=b.left:h.left=-b.left)}).then(function(){return Promise.resolve({width:d,height:f,margins:h})})}return Promise.resolve({height:b.height||250,margins:a.G})}
function oa(a,b,c){b=Object.assign(q({layout:c?"fixed":"fixed-height",height:"0",width:c?c:"auto","class":"i-amphtml-layout-awaiting-size"}),b,a.K);return M(a.ampdoc.win.document,"amp-ad",b)}function ra(a,b){var c=b.placements;if(!c)return y().info("amp-auto-ads","No placements in config"),[];var d=[];c.forEach(function(b){sa(a,b,d)});return d}
function sa(a,b,c){var d=na[b.pos];if(d){var e=b.anchor;if(e){var f=Q(a.getRootNode(),e);if(f.length){var h=void 0;if(b.style){var r=parseInt(b.style.top_m,10),w=parseInt(b.style.bot_m,10);if(r||w)h={top:r||void 0,bottom:w||void 0}}f.forEach(function(e){if(ta(e,b.pos)){var f=A(b,"attributes");c.push(new P(a,e,b.pos,d,f,h))}})}else y().warn("amp-auto-ads","No anchor element found")}else y().warn("amp-auto-ads","No anchor in placement")}else y().warn("amp-auto-ads","No injector for position")}
function Q(a,b){var c=b.selector;if(!c)return y().warn("amp-auto-ads","No selector in anchor"),[];c=[].slice.call(ka(a.documentElement||a,c));var d=b.min_c||0;0<d&&(c=c.filter(function(a){return a.textContent.length>=d}));"number"!=typeof b.index&&b.all||(c=(c=c[b.index||0])?[c]:[]);if(0==c.length)return[];if(b.sub){var e=[];c.forEach(function(a){e=e.concat(Q(a,b.sub))});return e}return c}
function ta(a,b){var c=1==b||4==b?a.parentElement:a;if(!c)return y().warn("amp-auto-ads","Parentless anchor with BEFORE/AFTER position."),!1;var d=c;return!ma.some(function(a){return ja(d,a)?(y().warn("amp-auto-ads","Placement inside blacklisted ancestor: "+a),!0):!1})}function qa(a,b){var c=100,d=Math.min(300,b),e=Math.round(a/1.2);return Math.min(Math.max(e,c),d)};function R(a){var b=4096,c,d=[],e=c&&null!=c.value&&""!==c.value?encodeURIComponent(c.name)+"="+encodeURIComponent(String(c.value)):null,f=b-45;e&&(f-=e.length+1);for(var h=Object.keys(a),r=0;r<h.length;r++){var w=h[r],K=a[w];if(null!=K&&""!==K){var t=encodeURIComponent(w)+"=",m=encodeURIComponent(String(K)),C=t.length+m.length+1;if(C>f){var W=m.substr(0,f-t.length-1).replace(/%\w?$/,"");W&&d.push(t+W);e&&d.push(e);break}d.push(t+m);f-=C}}return d.length?"//pagead2.googlesyndication.com/getconfig/ama?"+
d.join("&"):"//pagead2.googlesyndication.com/getconfig/ama"};function ua(a,b){return"adsense"==a?new S(b):"doubleclick"==a?new T(b):null}function S(a){this.h=a}g=S.prototype;g.isEnabled=function(){return!0};g.isResponsiveEnabled=function(){return!0};g.getConfigUrl=function(){var a=I(this.h,"documentInfo").get(),b=F(a.canonicalUrl).hostname;return R({client:this.h.getAttribute("data-ad-client"),plah:b,ama_t:"amp",url:a.canonicalUrl})};
g.getAttributes=function(){var a=q({type:"adsense","data-ad-client":this.h.getAttribute("data-ad-client")}),b=this.h.getAttribute("data-ad-host");b&&(a["data-ad-host"]=b);return a};g.getDefaultAdConstraints=function(){var a=N(this.h).getSize().height;return{initialMinSpacing:a,subsequentMinSpacing:[{adCount:3,spacing:2*a},{adCount:6,spacing:3*a}],maxAdCount:8}};g.getSizing=function(){return{}};function T(a){this.h=a}g=T.prototype;g.isEnabled=function(){return!0};g.isResponsiveEnabled=function(){return!1};
g.getConfigUrl=function(){var a=I(this.h,"documentInfo").get(),b=F(a.canonicalUrl).hostname;return R({client:this.h.getAttribute("data-ad-legacy-client"),plah:b,ama_t:"amp",url:a.canonicalUrl})};g.getAttributes=function(){return q({type:"doubleclick","data-slot":this.h.getAttribute("data-slot"),json:this.h.getAttribute("data-json")})};
g.getDefaultAdConstraints=function(){var a=N(this.h).getSize().height;return{initialMinSpacing:a,subsequentMinSpacing:[{adCount:3,spacing:2*a},{adCount:6,spacing:3*a}],maxAdCount:8}};g.getSizing=function(){var a=this.h.getAttribute("data-experiment");try{var b=JSON.parse(a)}catch(d){b=null}var c=b;return c?{height:c.height?Number(c.height):250,width:c.width?Number(c.width):void 0}:{}};function U(a,b,c,d,e){e=void 0===e?!1:e;this.L=a.slice(0);this.B=b;this.V=c;this.l=d;this.F=0;this.R=e}U.prototype.run=function(){var a=this;return this.l.isMaxAdCountReached()?ha(function(){return va(a)}):wa(this).then(function(b){return b?a.run():va(a)})};function va(a){return{adsPlaced:a.F,totalAdsOnPage:a.l.getAdCount()}}
function wa(a){var b=a.L.shift();return b?b.placeAd(a.B,a.V,a.l,a.R).then(function(c){return 2==c?(a.l.addAd(b.getAdElement()),a.F++,!0):wa(a)}):(y().info("amp-auto-ads","unable to fulfill ad strategy"),Promise.resolve(!1))};function V(a,b){this.m=a;this.O=b.initialMinSpacing;this.I=b.subsequentMinSpacing.slice(0).sort(function(a,b){return a.adCount-b.adCount});this.S=b.maxAdCount;this.H=xa(this)}V.prototype.addAd=function(a){this.m.push(a);this.H=xa(this)};V.prototype.getAdCount=function(){return this.m.length};V.prototype.isMaxAdCountReached=function(){return this.getAdCount()>=this.S};V.prototype.isTooNearAnAd=function(a){return ya(this,a,0)};
function ya(a,b,c){return c>=a.m.length?Promise.resolve(!1):za(b,a.m[c]).then(function(d){return d<a.H?!0:ya(a,b,c+1)})}function za(a,b){return O(b).then(function(b){return a>=b.top&&a<=b.bottom?0:Math.min(Math.abs(a-b.top),Math.abs(a-b.bottom))})}function xa(a){for(var b=a.getAdCount(),c=a.O,d=0;d<a.I.length;d++){var e=a.I[d];e.adCount<=b&&(c=e.spacing)}return c}
function Aa(a){return[].slice.call(a.getRootNode().querySelectorAll("AMP-AD")).filter(function(a){return a.parentElement&&"AMP-STICKY-AD"==a.parentElement.tagName?!1:!0})}
function Ba(a,b){b=b.adConstraints;if(!b)return null;var c=N(a).getHeight(),d=Ca(b.initialMinSpacing,c);if(null==d)return y().warn("amp-auto-ads","Invalid initial min spacing"),null;var e=(b.subsequentMinSpacing||[]).map(function(a){var b=a.adCount;if(null==b)return y().warn("amp-auto-ads","No subsequentMinSpacing adCount specified"),null;a=Ca(a.spacing,c);return null==a?(y().warn("amp-auto-ads","Invalid subsequent min spacing"),null):{adCount:b,spacing:a}});return-1!=e.indexOf(null)?null:null==b.maxAdCount?
(y().warn("amp-auto-ads","No maxAdCount specified"),null):{initialMinSpacing:d,subsequentMinSpacing:e,maxAdCount:b.maxAdCount}}function Ca(a,b){if(!a)return null;var c=parseFloat(a);return isNaN(c)||0>c?null:u(a,"px")?c:u(a,"vp")?c*b:null};function Da(a,b,c){this.ampdoc=a;this.B=b;this.N=c}
Da.prototype.run=function(){if(this.ampdoc.getRootNode().querySelector("AMP-STICKY-AD"))return y().warn("amp-auto-ads","Auto ads may not work because of already existing <amp-sticky-ad>."),Promise.resolve(!1);if(!y().assertArray(this.N.optInStatus||[]).includes(2))return Promise.resolve(!1);G(this.ampdoc.win,"extensions").installExtensionForDoc(this.ampdoc,"amp-sticky-ad","1.0");var a=N(this.ampdoc).getWidth(),b=Object.assign({},this.B,q({width:String(a),height:"100"}));a=this.ampdoc.win.document;
b=M(a,"amp-ad",b);a=M(a,"amp-sticky-ad",q({layout:"nodisplay"}));a.appendChild(b);b=this.ampdoc.getBody();b.insertBefore(a,b.firstChild);return Promise.resolve(!0)};function X(){return AMP.BaseElement.apply(this,arguments)||this}var Y=AMP.BaseElement;X.prototype=aa(Y.prototype);X.prototype.constructor=X;if(p)p(X,Y);else for(var Z in Y)if("prototype"!=Z)if(Object.defineProperties){var Ea=Object.getOwnPropertyDescriptor(Y,Z);Ea&&Object.defineProperty(X,Z,Ea)}else X[Z]=Y[Z];X.W=Y.prototype;
X.prototype.buildCallback=function(){var a=this,b=this.element.getAttribute("type");z(b,"Missing type attribute");var c=ua(b,this.element);z(c,"No AdNetworkConfig for type: "+b);if(c.isEnabled(this.win)){var d=this.getAmpDoc();G(this.win,"extensions").installExtensionForDoc(d,"amp-ad");var e=I(this.getAmpDoc(),"viewer"),f=e.whenFirstVisible();f.then(function(){return Fa(a,c.getConfigUrl())}).then(function(b){if(b){var e=b.noConfigReason;if(e)a.user().warn("amp-auto-ads",e);else{var f=ra(d,b),h=Object.assign(c.getAttributes(),
A(b,"attributes")),t=c.getSizing(),m=Ba(d,b)||c.getDefaultAdConstraints();m=new V(Aa(d),m);(new U(f,h,t,m,c.isResponsiveEnabled())).run();var C=Object.assign(h,A(b,"stickyAdAttributes"));(new Da(d,C,b)).run()}}})}};X.prototype.isLayoutSupported=function(){return!0};
function Fa(a,b){var c={mode:"cors",method:"GET",credentials:"omit"};return G(a.win,"xhr").fetchJson(b,c).then(function(a){return a.json()}).catch(function(b){a.user().error("amp-auto-ads","amp-auto-ads config xhr failed: "+b);return null})}(function(a){a.registerElement("amp-auto-ads",X)})(self.AMP);
})});

//# sourceMappingURL=amp-auto-ads-0.1.js.map
